#! /bin/bash

if [[ "$#" -lt 2 ]]		
then
  echo 'usage: grepdir.sh directory pattern [-grep option]*'
else
  if [ ! -d "$1" ]
  then 
    echo 'usage: grepdir.sh directory pattern [-grep option]*'
  else	
  	if [ -z "$3" ]
  	then
		temp1="grep \"$2\" {}"  #{} before "
		#echo $temp1
  	  #find "$1" -exec $temp1 \; 2>/dev/null
		grep -h $2 $1/*
  	elif [[ -n "$3" && "$3" == -* ]]
  	then
		
		temp2="grep $3 \"$2\""
		
		temp3="find \"$1\""
	  grep $3 $2 $1/*	
  	  #find "$1" -exec grep $3 "$2" {} \; 2>/dev/null

  	elif [[ -n "$4" && "$4" == -.* ]]
  	then
		temp4="grep $5 \"$4\""
		
		temp5="find \"$1\""
	  grep $4 $3 $2 $1/*
  	  #find "$1" -exec grep "$4" "$3" "$2" {} \; 2>/dev/null
	
  	fi
  fi
fi
